### ISSUE TITLE
[Bug] Villager in spruce cabin have emerald trade [Fabric 1.19.2]

### ISSUE THREAD

**Issue by xR4YM0ND** [NovaWostra/Dungeons-and-Taverns#1]
We have Numismatic Overhaul installed and have changed all trades to use custom trades with coins.

But in the cozy spruce cabin there is a Butcher Villager that has normal vanilla trades with emeralds.

Is there a way we or you could fix this?

BTW playing on a Server
If you need a latest client / server log , let me know

**Comment by xR4YM0ND** [comment]
He is expert from ground up:
![2023-05-07_22 09 30](https://user-images.githubusercontent.com/97298005/236700508-4aa4262e-7267-4494-9955-c1478d03c24a.png)

But he should be Novice and have trades like this:
![2023-05-07_22 09 36](https://user-images.githubusercontent.com/97298005/236700534-75b08143-8cd3-4e4b-9220-fe61f03730f6.png)

**Comment by NovaWostra** [comment]
you will run into this issue with the other taverns and villager from
taverns too. maybe even the stronghold zombie villagers. simply those
villagers where created using an /summon comand and have the trades
pre-placed in their nbt entity file. i cant fix it from my side but you can
fix it from your side by opening the individual NBT files of the structure
files containing villager and removing their trades in the nbt file entry
for their entity... or just remove them outright.

Right now i am unfortunely busy with personal family matters and do not
have the time to look into this.

with regards
Nova

xR4YM0ND ***@***.***> schrieb am So., 7. Mai 2023, 22:12:

**Comment by xR4YM0ND** [comment]
So you mean we could overwrite this nbt files via a datapack and we could provide that than with your mod (just the nbt changed) in our modpack on modrinth?

Have a great time with your fam <3
Thank you for answering
