### ISSUE TITLE
[Console Entries] Couldn't parse loot table + empty or non-existent pool [Fabric 1.19.2]

### ISSUE THREAD

**Issue by xR4YM0ND** [NovaWostra/Dungeons-and-Taverns#2]
Some console entries:

Line 518 `Couldn't parse data file nova_structures:chests/water_supply`

Line 546 `Found validation problem in {nova_structures:chests/mangrove_witchhud}.pools[1].entries[2]->{minecraft:entities/witch}.pools[0].entries[3].functions[1]: Parameters [<parameter minecraft:killer_entity>] are not provided in this context`

Line 746 `[21:32:33] [Worker-Main-5/WARN]: Empty or non-existent pool: minecraft:`

[server latest.log](https://gist.github.com/xR4YM0ND/10a249681c2a3b4a2f97898dd2f24550)

**Comment by xR4YM0ND** [comment]
So Line 518 `Couldn't parse data file nova_structures:chests/water_supply` ~ you missed a comma

Line 546 `Found validation problem in {nova_structures:chests/mangrove_witchhud}.pools[1].entries[2]->{minecraft:entities/witch}.pools[0].entries[3].functions[1]: Parameters [<parameter minecraft:killer_entity>] are not provided in this context` ~ i deleted the witch entity loot table (needs something like killer entity ?) 

But Line 746 `Empty or non-existent pool: minecraft:` ~ idk what to do with this .. is it a structure problem (jigsaw or so) or a loot table problem? I can't figure it out ...

**Comment by suerion** [comment]
dupplicated #3  and #4

**Comment by suerion** [comment]
> So Line 518 `Couldn't parse data file nova_structures:chests/water_supply` ~ you missed a comma
> 
> Line 546 `Found validation problem in {nova_structures:chests/mangrove_witchhud}.pools[1].entries[2]->{minecraft:entities/witch}.pools[0].entries[3].functions[1]: Parameters [<parameter minecraft:killer_entity>] are not provided in this context` ~ i deleted the witch entity loot table (needs something like killer entity ?)
> 
> But Line 746 `Empty or non-existent pool: minecraft:` ~ idk what to do with this .. is it a structure problem (jigsaw or so) or a loot table problem? I can't figure it out ...

did you fix the first 2 issues? don't found the missed comma, would you add an pull request?

**Comment by xR4YM0ND** [comment]
Seems like the version 2.0.2 is not pushed to github yet. 
The missing comma is in the water_supply.json in line 16

Is: `}`
Should be `},`



For the witch problem i just deleted the witch entity loot table from the loot_table
I removed:
```{
          "type": "minecraft:loot_table",
          "weight": 30,
          "name": "minecraft:entities/witch"
}```

and deleted the last comma.


For the Villager problem i changed all villagers to spawn like in vanilla & now they apply the jobs on their own and have numismatic trades (in our case)
